config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users

  root 'tweets#index'

  get 'tweets/:tweet_id/likes' => 'likes#create'
  get 'tweets/:tweet_id/likes/:id' => 'likes#destroy'
  resources :perfumes
  resources :users, only: [:show]
  resources :tweets do
    collection do
      get 'toudai'
      get 'toukoudai'
      get 'hitotubashi'
      get 'yokokoku'
      get 'waseda'
      get 'aogaku'
      get 'keio'
      get 'meiji'
      get 'sophia'
      get 'rikadai'
      get 'rikkyo'
      get 'chuo'
      get 'housei'
      get 'gakushuin'
      get 'nitidai'
      get 'toyo'
      get 'komazawa'
      get 'senshu'
      get 'seikei'
      get 'seijo'
      get 'meigaku'
      get 'dokkyou'
      get 'kokugakuin'
      get 'musashi'
      get 'tokai'
      get 'daitobunka'
      get 'teikyo'
      get 'kokushikan'
      get 'asia'
      

    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]

    
     end
  
   resources :maps, only: [:index]


end

 

app/models/tweet.rb
class Tweet < ApplicationRecord

    mount_uploader :image, ImageUploader
  
    belongs_to :user  
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # before_action :validate_id, only: :show
  before_action :authenticate_user!, only: [:new, :create]

    def index
        @tweets = Tweet.includes(:user).all
    end

    def index
      @tweets = Tweet.order(created_at: :desc)
    end

    def waseda
      @tweets = Tweet.order(created_at: :desc)
    end

    def keio
      @tweets = Tweet.order(created_at: :desc)
    end


    def new
        @tweet = Tweet.new
      end
    
      def create
        tweet = Tweet.new(tweet_params)

        tweet.user_id = current_user.id 

        if tweet.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @tweet = Tweet.find(params[:id])
        @comments = @tweet.comments
        @comment = Comment.new
        rescue ActiveRecord::RecordNotFound
        flash[:alert] = "Tweet not found"
        redirect_to tweets_path

      end

      def edit
        @tweet = Tweet.find(params[:id])
      end

      def update
        tweet = Tweet.find(params[:id])
        if tweet.update(tweet_params)
          redirect_to :action => "show", :id => tweet.id
        else
          redirect_to :action => "new"
        end
      end
    
      def destroy
        tweet = Tweet.find(params[:id])
        tweet.destroy
        redirect_to action: :index
      end

      def toudai
        @tweets = Tweet.where(access: '東京大学')
      end

      def toukoudai
        @tweets = Tweet.where(access: '東京工業大学大学')
      end

      def hitotubashi
        @tweets = Tweet.where(access: '一橋大学')
      end

      def yokokoku
        @tweets = Tweet.where(access: '横浜国立大学')
      end

      def waseda
        @tweets = Tweet.where(access: '早稲田大学')
      end

      def keio
        @tweets = Tweet.where(access: '慶応義塾大学')
      end

      def sophia
        @tweets = Tweet.where(access: '上智大学')
      end

      def rikadai
        @tweets = Tweet.where(access: '東京理科大学')
      end

      def meiji
        @tweets = Tweet.where(access: '明治大学')
      end

      def aogaku
        @tweets = Tweet.where(access: '青山学院大学')
      end

      def rikkyo
        @tweets = Tweet.where(access: '立教大学')
      end

      def chuo
        @tweets = Tweet.where(access: '中央大学')
      end

      def housei
        @tweets = Tweet.where(access: '法政大学')
      end

      def gakushuin
        @tweets = Tweet.where(access: '学習院大学')
      end

      def nihon
        @tweets = Tweet.where(access: '日本大学')
      end

      def toyo
        @tweets = Tweet.where(access: '東洋大学')
      end
      
      def komazawa
        @tweets = Tweet.where(access: '駒澤大学')
      end

      def senshu
        @tweets = Tweet.where(access: '専修大学')
      end

      def seijo
        @tweets = Tweet.where(access: '成城大学')
      end

      def seikei
        @tweets = Tweet.where(access: '成蹊大学')
      end

      def meigaku
        @tweets = Tweet.where(access: '明治学院大学')
      end

      def meigaku
        @tweets = Tweet.where(access: '獨協大学')
      end

      def kokugakuin
        @tweets = Tweet.where(access: '國学院大学')
      end

      def musashi
        @tweets = Tweet.where(access: '武蔵大学')
      end

      def tokai
        @tweets = Tweet.where(access: '東海大学')
      end

      def daitobunka
        @tweets = Tweet.where(access: '大東文化大学')
      end

      def asia
        @tweets = Tweet.where(access: '亜細亜大学')
      end

      def teikyo
        @tweets = Tweet.where(access: '帝京大学')
      end

      def kokushikan
        @tweets = Tweet.where(access: '国士館大学')
      end





      private
      def tweet_params
        params.require(:tweet).permit(:shop, :genre, :access,:about,:menu,:image, :star)
      end
    end

app/helpers/tweets_helper.rb
module TweetsHelper

    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end
     
end

app/views/tweets/aogaku.html.erb
<div class="tweets-container">
 <% @tweets.each do |t| %>
   <div class="tweet">
   <%= image_tag t.image_url, size: "250x200" if t.image? %>
   


    <div>
    <h2>総合評価
    <span class="star-rating">
       <span class="star-rating-front" style="width: <%= getPercent(t.star) %>%;">★★★★★</span>
       <span class="star-rating-back">★★★★★</span>
    </span> 
    </h2>
    </div>
    
    
    <% if user_signed_in? %>
    <% if current_user.already_liked?(t) %>
        <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
          <i class="fas fa-heart liked-heart"></i><%= t.likes.count %>
        <% end %>
    <% else %>
        <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
          <i class="far fa-heart unliked-heart"></i><%= t.likes.count %>
        <% end %>
    <% end %>
<% else %>
    <i class="far fa-heart unliked-heart"></i><%= t.likes.count %>
<% end %>

    <h7>店名：<h7>
    <%= t.shop %><br>
    <h7>ジャンル：<h7>
    <%= t.genre %><br>
    <h7>大学名：<h7><%= t.access %><br>
    <h7>レビュー：<h7><%= t.about %><br>
    <h7>おすすめメニュー：<h7><%= t.menu %>

   


      <%= t.created_at %>
      <%= link_to "詳細へ", tweet_path(t.id), class: 'button' %>

      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_tweet_path(t.id),class: 'button' %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete,class: 'button' %>
  
      <% end %> 

    </div>
  <% end %>
</div>


<%= link_to "TOPに戻る", tweets_path, class: 'button' %>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id),class: 'button'  %>
<% end %>

</body>

app/views/tweets/asia.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/chuo.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/komazawa.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/meiji.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/new.html.erb
<div class="sinki-toukou">

<h1></h1> 
<div class="form-container">
<h3>新規投稿ページ</h3>
<%= form_for @tweet do |f| %>

  

    <div class="field">
    <%= f.label :お店の名前 %>
    <%= f.text_field :shop, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :画像 %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
  <%= f.label :ジャンル  %>
  <%= f.select :genre, 
  [["ラーメン", "ラーメン"], 
  ["油そば", "油そば"], 
  ["うどん", "うどん"],
  ["そば", "そば"],
  ["まぜそば", "まぜそば"],
  ["つけ麺", "つけ麺"],
  ["洋食", "洋食"],
  ["中華", "中華"],
  ["韓国", "韓国"],
  ["エスニック", "エスニック"],
  ["カレー", "カレー"],
  ["しゃぶしゃぶ", "しゃぶしゃぶ"],
  ["すきやき", "すきやき"],
  ["鍋", "鍋"],
  ["カフェ", "カフェ"],
  ["喫茶店", "喫茶店"],
  ["寿司", "寿司"],
  ["焼き鳥", "焼き鳥"],
  ["丼", "丼"],
  ["うなぎ", "うなぎ"],
  ["とんかつ", "とんかつ"],
  ["てんぷら", "てんぷら"],
  ["焼肉", "焼肉"],
  ["居酒屋", "居酒屋"],

  ["イタリアン", "イタリアン"]],include_blank: "選択して下さい" %>
</div>

<div class="field">
    <%= f.label :大学名  %>
    <%= f.select :access, 
    [["東京大学", "東京大学"],
    ["東京工業大学", "東京工業大学"],
    ["一橋大学", "一橋大学"],
    ["横浜国立大学", "横浜国立大学"],
    ["早稲田大学", "早稲田大学"], 
    ["慶応義塾大学", "慶応義塾大学"],
    ["上智大学", "上智大学"],
    ["東京理科大学", "東京理科大学"],
    ["明治大学", "明治大学"],
    ["青山学院大学", "青山学院大学"],
    ["立教大学", "立教大学"], 
    ["法政大学", "法政大学"], 
    ["学習院大学", "学習院大学"],
    ["日本大学", "日本大学"],
    ["東洋大学", "東洋大学"], 
    ["駒澤大学", "駒澤大学"], 
    ["専修大学", "専修大学"],
    ["成蹊大学", "成蹊大学"],
    ["成城大学", "成城大学"],
    ["明治学院大学", "明治学院大学"],
 ["獨協大学", "獨協大学"],
["國學院大学", "國學院大学"],
["武蔵大学", "武蔵大学"],
["大東文化大学", "大東文化大学"],
["亜細亜大学", "亜細亜大学"],
["帝京大学", "帝京大学"],
["国士館大学", "国士館大学"],
["東海大学", "東海大学"]],include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :レビュー %>
    <%= f.text_field :about, :size => 30 %>
  </div>


  <h5 class="rating-title">総合評価</h5>
<div class="post_form">
  <%= f.radio_button :star, 5, id: 'star1' %>
  <label for="star1">★</label>

  <%= f.radio_button :star, 4, id: 'star2' %>
  <label for="star2">★</label>

  <%= f.radio_button :star, 3, id: 'star3' %>
  <label for="star3">★</label>

  <%= f.radio_button :star, 2, id: 'star4' %>
  <label for="star4">★</label>

  <%= f.radio_button :star, 1, id: 'star5' %>
  <label for="star5">★</label>
</div>


  <div class="field">
    <%= f.label :おすすめメニュー %>
    <%= f.text_field :menu, :size => 30 %>
  </div>
 <%= f.submit "ごはんレビューを投稿する", class: 'button'%>
 </div>
 <% end %>
 </div>

<%= link_to "TOPに戻る", tweets_path, class: 'button' %>

</div>

app/views/tweets/nitidai.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/seijo.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/senshu.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/teikyo.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/toudai.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/toukoudai.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/toyo.html.erb
<% @tweets.each do |t| %>
    <div class="tweet">
     <%= t.user.email %>
 
 
     <%= image_tag t.image_url, size: "250x200" if t.image? %>
     
     <%= t.about %>
     <%= link_to "詳細へ", tweet_path(t.id) %>
     <%= t.shop %>
     <%= t.genre %>
     <%= t.access %>
     <%= t.about %>
     <%= t.menu %>
 
       <% if user_signed_in? %>
       <% if current_user.already_liked?(t) %>
           <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
             <i class="fas fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% else %>
           <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
             <i class="far fa-heart"></i><%= t.likes.count %>
           <% end %>
       <% end %>
   <% else %>
   <i class="far fa-heart"></i><%= t.likes.count %>
 <% end %>
 
       <%= t.created_at %>
       <%= link_to "詳細へ", tweet_path(t.id) %>
 
       <% if user_signed_in? && current_user.id == t.user_id %>
       <%= link_to "編集する", edit_tweet_path(t.id) %>
       <%= link_to "削除する", tweet_path(t.id), method: :delete %>
       <% end %> 
 
     </div>
   <% end %>

app/views/tweets/waseda.html.erb
<div class="tweets-container">
 <% @tweets.each do |t| %>
   <div class="tweet">
   <%= image_tag t.image_url, size: "250x200" if t.image? %>
   


    <div>
    <h2>総合評価
    <span class="star-rating">
       <span class="star-rating-front" style="width: <%= getPercent(t.star) %>%;">★★★★★</span>
       <span class="star-rating-back">★★★★★</span>
    </span> 
    </h2>
    </div>
    
    
    <% if user_signed_in? %>
    <% if current_user.already_liked?(t) %>
        <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
          <i class="fas fa-heart liked-heart"></i><%= t.likes.count %>
        <% end %>
    <% else %>
        <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
          <i class="far fa-heart unliked-heart"></i><%= t.likes.count %>
        <% end %>
    <% end %>
<% else %>
    <i class="far fa-heart unliked-heart"></i><%= t.likes.count %>
<% end %>

    <h7>店名：<h7>
    <%= t.shop %><br>
    <h7>ジャンル：<h7>
    <%= t.genre %><br>
    <h7>大学名：<h7><%= t.access %><br>
    <h7>レビュー：<h7><%= t.about %><br>
    <h7>おすすめメニュー：<h7><%= t.menu %>

   


      <%= t.created_at %>
      <%= link_to "詳細へ", tweet_path(t.id), class: 'button' %>

      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_tweet_path(t.id),class: 'button' %>
      <%= button_to "削除する", tweet_path(t.id), method: :delete,class: 'button' %>
  
      <% end %> 

    </div>
  <% end %>
</div>


<%= link_to "TOPに戻る", tweets_path, class: 'button' %>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id),class: 'button'  %>
<% end %>

</body>