config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users

  root 'tweets#index'

  get 'tweets/:tweet_id/likes' => 'likes#create'
  get 'tweets/:tweet_id/likes/:id' => 'likes#destroy'
  resources :perfumes
  resources :users, only: [:show]
  resources :tweets do
    collection do
      get 'toudai'
      get 'toukoudai'
      get 'hitotubashi'
      get 'yokokoku'
      get 'waseda'
      get 'aogaku'
      get 'keio'
      get 'meiji'
      get 'sophia'
      get 'rikadai'
      get 'rikkyo'
      get 'chuo'
      get 'housei'
      get 'gakushuin'
      get 'nitidai'
      get 'toyo'
      get 'komazawa'
      get 'senshu'
      get 'seikei'
      get 'seijo'
      get 'meigaku'
      get 'dokkyou'
      get 'kokugakuin'
      get 'musashi'
      get 'tokai'
      get 'daitobunka'
      get 'teikyo'
      get 'kokushikan'
      get 'asia'
      

    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]

    
     end
  
   resources :maps, only: [:index]


end

 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :tweets, dependent: :destroy 
         has_many :likes, dependent: :destroy
         has_many :comments, dependent: :destroy
  has_many :liked_tweets, through: :likes, source: :tweet

  def already_liked?(tweet)
    self.likes.exists?(tweet_id: tweet.id)
  end
  
         validates :name, presence: true
         validates :profile, length: { maximum: 200 } 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<h6>マイページ</h6>
<div class="user-info">
  <p>名前 : <%= @user.name %></p>
  <p>メールアドレス : <%= @user.email %></p>
  <p>プロフィール : <%= @user.profile %></p>

  <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path, class: 'button' %>
  <% end %>
</div>

<h6>あなたの投稿</h6>
<div class="user-tweets">
  <% @user.tweets.each do |t| %>
    <p><%= t.user.name %></p>
    <p><%= t.shop %></p>
    <p><%= t.menu %></p>
  <% end %>
</div>

<!-- 以下はいいね機能を実装している場合-->
<h6>いいねした投稿</h6>
<div class="liked-tweets">
  <% @user.liked_tweets.each do |t| %>
    <p><%= t.user.name %></p>
    <p><%= t.shop %></p>
  <% end %>
</div>
<!-- ここまで-->

<%= link_to "TOPに戻る", tweets_path, class: 'button' %>